"""Adiciona novos campos de recorrencia ao OrcamentoLancamento

Revision ID: 1fe4ffc4f011
Revises: 
Create Date: 2025-01-20 17:20:21.482126

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1fe4ffc4f011'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orcamento_lancamento', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dias_semana', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('tipo_repeticao_mensal', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('semana_do_mes', sa.Integer(), nullable=True))
        batch_op.drop_column('dia_fixo')
        batch_op.drop_column('dia_semana')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orcamento_lancamento', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dia_semana', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('dia_fixo', sa.INTEGER(), nullable=True))
        batch_op.drop_column('semana_do_mes')
        batch_op.drop_column('tipo_repeticao_mensal')
        batch_op.drop_column('dias_semana')

    # ### end Alembic commands ###
